/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATE_H_RPCGEN
#define _CALCULATE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct inputs {
	float num1;
	float num2;
	char operator;
};
typedef struct inputs inputs;
#ifdef __cplusplus
extern "C" bool_t xdr_inputs(XDR *, inputs*);
#elif __STDC__
extern  bool_t xdr_inputs(XDR *, inputs*);
#else /* Old Style C */
bool_t xdr_inputs();
#endif /* Old Style C */


#define CALCULATE_PROG ((rpc_uint)0x2fffffff)
#define CALCULATE_VER ((rpc_uint)1)

#ifdef __cplusplus
#define ADD ((rpc_uint)1)
extern "C" float * add_1(inputs *, CLIENT *);
extern "C" float * add_1_svc(inputs *, struct svc_req *);
#define SUB ((rpc_uint)2)
extern "C" float * sub_1(inputs *, CLIENT *);
extern "C" float * sub_1_svc(inputs *, struct svc_req *);
#define MUL ((rpc_uint)3)
extern "C" float * mul_1(inputs *, CLIENT *);
extern "C" float * mul_1_svc(inputs *, struct svc_req *);
#define DIV ((rpc_uint)4)
extern "C" float * div_1(inputs *, CLIENT *);
extern "C" float * div_1_svc(inputs *, struct svc_req *);
#define SQR ((rpc_uint)5)
extern "C" float * sqr_1(inputs *, CLIENT *);
extern "C" float * sqr_1_svc(inputs *, struct svc_req *);
#define SQT ((rpc_uint)6)
extern "C" float * sqt_1(inputs *, CLIENT *);
extern "C" float * sqt_1_svc(inputs *, struct svc_req *);
#define SIN ((rpc_uint)7)
extern "C" float * sin_1(inputs *, CLIENT *);
extern "C" float * sin_1_svc(inputs *, struct svc_req *);
#define COS ((rpc_uint)8)
extern "C" float * cos_1(inputs *, CLIENT *);
extern "C" float * cos_1_svc(inputs *, struct svc_req *);
#define TAN ((rpc_uint)9)
extern "C" float * tan_1(inputs *, CLIENT *);
extern "C" float * tan_1_svc(inputs *, struct svc_req *);
#define LOG ((rpc_uint)10)
extern "C" float * log_1(inputs *, CLIENT *);
extern "C" float * log_1_svc(inputs *, struct svc_req *);

#elif __STDC__
#define ADD ((rpc_uint)1)
extern  float * add_1(inputs *, CLIENT *);
extern  float * add_1_svc(inputs *, struct svc_req *);
#define SUB ((rpc_uint)2)
extern  float * sub_1(inputs *, CLIENT *);
extern  float * sub_1_svc(inputs *, struct svc_req *);
#define MUL ((rpc_uint)3)
extern  float * mul_1(inputs *, CLIENT *);
extern  float * mul_1_svc(inputs *, struct svc_req *);
#define DIV ((rpc_uint)4)
extern  float * div_1(inputs *, CLIENT *);
extern  float * div_1_svc(inputs *, struct svc_req *);
#define SQR ((rpc_uint)5)
extern  float * sqr_1(inputs *, CLIENT *);
extern  float * sqr_1_svc(inputs *, struct svc_req *);
#define SQT ((rpc_uint)6)
extern  float * sqt_1(inputs *, CLIENT *);
extern  float * sqt_1_svc(inputs *, struct svc_req *);
#define SIN ((rpc_uint)7)
extern  float * sin_1(inputs *, CLIENT *);
extern  float * sin_1_svc(inputs *, struct svc_req *);
#define COS ((rpc_uint)8)
extern  float * cos_1(inputs *, CLIENT *);
extern  float * cos_1_svc(inputs *, struct svc_req *);
#define TAN ((rpc_uint)9)
extern  float * tan_1(inputs *, CLIENT *);
extern  float * tan_1_svc(inputs *, struct svc_req *);
#define LOG ((rpc_uint)10)
extern  float * log_1(inputs *, CLIENT *);
extern  float * log_1_svc(inputs *, struct svc_req *);

#else /* Old Style C */
#define ADD ((rpc_uint)1)
extern  float * add_1();
extern  float * add_1_svc();
#define SUB ((rpc_uint)2)
extern  float * sub_1();
extern  float * sub_1_svc();
#define MUL ((rpc_uint)3)
extern  float * mul_1();
extern  float * mul_1_svc();
#define DIV ((rpc_uint)4)
extern  float * div_1();
extern  float * div_1_svc();
#define SQR ((rpc_uint)5)
extern  float * sqr_1();
extern  float * sqr_1_svc();
#define SQT ((rpc_uint)6)
extern  float * sqt_1();
extern  float * sqt_1_svc();
#define SIN ((rpc_uint)7)
extern  float * sin_1();
extern  float * sin_1_svc();
#define COS ((rpc_uint)8)
extern  float * cos_1();
extern  float * cos_1_svc();
#define TAN ((rpc_uint)9)
extern  float * tan_1();
extern  float * tan_1_svc();
#define LOG ((rpc_uint)10)
extern  float * log_1();
extern  float * log_1_svc();
#endif /* Old Style C */

#endif /* !_CALCULATE_H_RPCGEN */
