/*
* This is sample code generated by rpcgen.
* These are only templates and you can use them
* as a guideline for developing your own functions.
*server
*/

#include "calculate.h"


float calculate_prog_1( char *host, float number1, float number2, char operator, CLIENT *client ){

	float *result_1;
	inputs add_1_arg;
	float *result_2;
	inputs sub_1_arg;
	float *result_3;
	inputs mul_1_arg;
	float *result_4;
	inputs div_1_arg;
	float *result_5;
	inputs sqr_1_arg;
	float *result_6;
	inputs sqt_1_arg;
	float *result_7;
	inputs sin_1_arg;
	float *result_8;
	inputs cos_1_arg;
	float *result_9;
	inputs tan_1_arg;
	float *result_10;
	inputs log_1_arg;

	if(operator=='+'){

		add_1_arg.num1=number1;
		add_1_arg.num2=number2;
		add_1_arg.operator=operator;

		result_1 = add_1(&add_1_arg, client);
		if (result_1 == (float *) NULL) {
			client_perror (client, "call failed");
		}
		return *result_1;
	}
	else if(operator=='-'){

		sub_1_arg.num1=number1;
		sub_1_arg.num2=number2;
		sub_1_arg.operator=operator;

		result_2 = sub_1(&sub_1_arg, client);
		if (result_2 == (float *) NULL) {
			client_perror (client, "call failed");
		}
		return *result_2;
	}
	else if(operator=='*'){

		mul_1_arg.num1=number1;
		mul_1_arg.num2=number2;
		mul_1_arg.operator=operator;

		result_3 = mul_1(&mul_1_arg, client);
		if (result_3 == (float *) NULL) {
			client_perror (client, "call failed");
		}
		return *result_3;
	}
	else if(operator=='/'){

		div_1_arg.num1=number1;
		div_1_arg.num2=number2;
		div_1_arg.operator=operator;

		if(number2 == 0){
			printf("Division by zero is not valid.\n");
			exit(0);
		}else{

			result_4 = div_1(&div_1_arg, client);
			if (result_4 == (float *) NULL) {
				client_perror (client, "call failed");
			}
			return *result_4;
		}
	}
	else if(operator=='sqr'){

		sqr_1_arg.num1=number1;
		sqr_1_arg.operator=operator;

		result_5 = sqr_1(&sqr_1_arg, client);
		if (result_5 == (float *) NULL) {
			client_perror (client, "call failed");
		}
		return *result_5;
	}
	else if(operator=='sqt'){

		sqt_1_arg.num1=number1;
		sqt_1_arg.operator=operator;

		if(number1 <= 0){
			printf("Negative numbers don't have a square root.\n");
			exit(0);
		}else{

			result_6 = div_1(&sqt_1_arg, client);
			if (result_6 == (float *) NULL) {
				client_perror (client, "call failed");
			}
			return *result_6;
		}
	}
	else if(operator=='sin'){

		sin_1_arg.num1=number1;
		sin_1_arg.operator=operator;

		result_7 = div_1(&sin_1_arg, client);
		if (result_7 == (float *) NULL) {
			client_perror (client, "call failed");
		}
		return *result_7;
	}
	else if(operator=='cos'){

		cos_1_arg.num1=number1;
		cos_1_arg.operator=operator;

		result_8 = div_1(&cos_1_arg, client);
		if (result_8 ==(float *) NULL) {
			client_perror (client, "call failed");
		}
		return *result_8;
	}
	else if(operator=='tan'){

		tan_1_arg.num1=number1;
		tan_1_arg.operator=operator;

		result_9 = div_1(&tan_1_arg, client);
		if (result_9 == (float *) NULL) {
			client_perror (client, "call failed");
		}
		return *result_9;
	}
	else if(operator=='log'){

		log_1_arg.num1=number1;
		log_1_arg.operator=operator;

		if(number1 != 0){
			printf("Logarithm of 0 is not vaild.\n");
			exit(0);
		}else{
		result_10 = div_1(&log_1_arg, client);
		if (result_10 == (float *) NULL) {
			client_perror (client, "call failed");
		}
			return *result_10;
		}
	}
}

int main (int argc, char *argv[])
{
	char *host;
	float num1,num2;
	char opr;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	printf("Welcome to RPCcalculator!!!\n");
	printf("+ for Addition\n- for Substraction\n* for Multiplication\n/ for Division\nsqr for Square\nsqt for Square Root\nsin for Sine\ncos for Cosine\ntan for Tangent\nlog for Logarithm");
	printf("Enter the Operator :\n");
	scanf("%s",&opr);
	printf("Enter number 1 :\n");
	scanf("%f",&num1);
	if (opr == "+" || opr == "-" || opr == "*" || opr == "/") {
		printf("Enter number 2 :\n");
		scanf("%f",&num2);
	}

	host = argv[1];

	clnt = client_create (host, CALCULATE_PROG, CALCULATE_VER, "udp");

	if (clnt == NULL) {
		client_pcreateerror (host);
		exit (1);
	}

	printf("The Answer = %f\n",calculate_prog_1 (host,num1,num2,opr,clnt));

	client_destroy (clnt);

	exit (0);
}
