/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h>
#include "calculate.h"

/* Default timeout can be changed using client_control() */
static struct timeval TIMEOUT = { 25, 0 };

float *
add_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, ADD, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
sub_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, SUB, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
mul_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, MUL, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
div_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, DIV, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
sqr_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, SQR, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
sqt_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, SQT, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
sin_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, SIN, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
cos_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, COS, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
tan_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, TAN, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}

float *
log_1(inputs *argp, CLIENT *client)
{
	static float client_res;

	memset((char *)&client_res, 0, sizeof(client_res));
	if (client_call(client, LOG, xdr_inputs, argp, xdr_float, &client_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&client_res);
}
